
import { test } from 'node:test';
import * as assert from 'node:assert';
import { safeJsonParse } from '../lib/utils';

test('safeJsonParse', async (t) => {
  await t.test('parses simple JSON array', () => {
    const input = '["a", "b"]';
    assert.deepStrictEqual(safeJsonParse(input), ["a", "b"]);
  });

  await t.test('parses simple JSON object', () => {
    const input = '{"key": "value"}';
    assert.deepStrictEqual(safeJsonParse(input), { key: "value" });
  });

  await t.test('parses JSON embedded in conversational text (Array)', () => {
    const input = 'Here is the list: ["item1", "item2"]. Hope that helps!';
    assert.deepStrictEqual(safeJsonParse(input), ["item1", "item2"]);
  });

  await t.test('parses JSON embedded in conversational text (Object)', () => {
    const input = 'Sure, here is the object: {"id": 123, "active": true} (generated by AI)';
    assert.deepStrictEqual(safeJsonParse(input), { id: 123, active: true });
  });

  await t.test('handles nested structures', () => {
    const input = 'Outer [ {"inner": [1, 2]} ] end.';
    assert.deepStrictEqual(safeJsonParse(input), [{ inner: [1, 2] }]);
  });

  await t.test('handles brackets inside strings', () => {
    const input = 'Text ["This has [brackets] inside"] end.';
    assert.deepStrictEqual(safeJsonParse(input), ["This has [brackets] inside"]);
  });

  await t.test('handles escaped quotes inside strings', () => {
    const input = 'Text ["String with \\"quotes\\" inside"] end.';
    assert.deepStrictEqual(safeJsonParse(input), ["String with \"quotes\" inside"]);
  });

  await t.test('returns first valid JSON structure found (Array first)', () => {
    const input = 'First [1, 2] then {a: 1}';
    assert.deepStrictEqual(safeJsonParse(input), [1, 2]);
  });

  await t.test('returns first valid JSON structure found (Object first)', () => {
    const input = 'First {"a": 1} then [1, 2]';
    assert.deepStrictEqual(safeJsonParse(input), { a: 1 });
  });

  await t.test('returns null for malformed JSON', () => {
    const input = 'Here is [unfinished';
    assert.strictEqual(safeJsonParse(input), null);
  });

  await t.test('returns null for balanced but invalid JSON', () => {
    const input = 'Here is [1, 2,]'; // Trailing comma is invalid in standard JSON
    assert.strictEqual(safeJsonParse(input), null);
  });

  await t.test('handles malformed brackets', () => {
     const input = 'Text [1, 2]] end'; // Extra closing bracket
     // The parser stops at the matching bracket, so it sees `[1, 2]`.
     // The remaining `] end` is ignored.
     assert.deepStrictEqual(safeJsonParse(input), [1, 2]);
  });

  await t.test('handles incomplete nested structure', () => {
      const input = 'Text [1, {a: 2] end'; // Missing closing brace
      assert.strictEqual(safeJsonParse(input), null);
  });
});
