
import { GoogleGenAI } from "@google/genai";
import blogData from "./blog_data.json";

/**
 * @fileoverview RAG (Retrieval-Augmented Generation) Logic
 *
 * This module handles the retrieval part of the RAG pipeline. It:
 * 1. Takes a user query.
 * 2. Generates an embedding for that query using Google's Gemini Text Embedding model.
 * 3. Compares the query embedding against a database of pre-calculated embeddings (from blog posts).
 * 4. Returns the most semantically similar text chunks to be used as context for the LLM.
 *
 * Dependencies:
 * - `blog_data.json`: A JSON file generated by `scripts/ingest_blog.ts` containing text chunks and their embeddings.
 */

/**
 * Calculates the magnitude (Euclidean norm) of a vector.
 * @param vec - The vector.
 * @returns The magnitude.
 */
export function magnitude(vec: number[]): number {
  let sum = 0;
  for (let i = 0; i < vec.length; i++) {
    sum += vec[i] * vec[i];
  }
  return Math.sqrt(sum);
}

/**
 * Calculates the dot product of two vectors.
 * @param vecA - The first vector.
 * @param vecB - The second vector.
 * @returns The dot product.
 */
export function dotProduct(vecA: number[], vecB: number[]): number {
  let product = 0;
  for (let i = 0; i < vecA.length; i++) {
    product += vecA[i] * vecB[i];
  }
  return product;
}

/**
 * Calculates the cosine similarity between two vectors.
 *
 * Cosine similarity measures the cosine of the angle between two non-zero vectors.
 * It is a judgment of orientation and not magnitude: two vectors with the same orientation
 * have a cosine similarity of 1, two vectors oriented at 90° relative to each other have
 * a similarity of 0, and two vectors diametrically opposed have a similarity of -1.
 *
 * In the context of semantic search, a higher cosine similarity indicates that two text
 * embeddings are semantically closer.
 *
 * @param vecA - The first vector (e.g., query embedding).
 * @param vecB - The second vector (e.g., document chunk embedding).
 * @param magA - Optional pre-calculated magnitude of vecA.
 * @param magB - Optional pre-calculated magnitude of vecB.
 * @returns A number between -1 and 1 representing the similarity.
 *          Returns 0 if dimensions mismatch or magnitude is zero to prevent errors.
 */
export function cosineSimilarity(vecA: number[], vecB: number[], magA?: number, magB?: number): number {
  if (vecA.length !== vecB.length || vecA.length === 0) return 0;

  const dot = dotProduct(vecA, vecB);
  const mA = magA ?? magnitude(vecA);
  const mB = magB ?? magnitude(vecB);

  if (mA === 0 || mB === 0) return 0;

  return dot / (mA * mB);
}

export interface BlogChunk {
  id: string;
  text: string;
  url: string;
  title: string;
  publishedDate: string;
  embedding?: number[];
  // Optimization: Pre-calculated magnitude for the embedding
  _magnitude?: number;
}

export interface RelevantChunk {
  text: string;
  title: string;
  url: string;
  score: number;
}

// Lazy initialization of blog data with magnitudes
let cachedBlogData: BlogChunk[] | null = null;

const getBlogData = (): BlogChunk[] => {
  if (cachedBlogData) return cachedBlogData;

  // Optimization: Filter out chunks without embeddings during initialization
  // and pre-calculate magnitude for valid chunks.
  // This avoids checking `chunk.embedding` exists in the hot loop.
  cachedBlogData = (blogData as BlogChunk[]).reduce<BlogChunk[]>((acc, chunk) => {
    if (chunk.embedding && chunk.embedding.length > 0) {
      acc.push({
        ...chunk,
        _magnitude: magnitude(chunk.embedding)
      });
    }
    return acc;
  }, []);

  return cachedBlogData;
};

/**
 * Retrieves relevant context chunks for a given query.
 *
 * This function performs the following steps:
 * 1. Embeds the user's query using the `text-embedding-004` model.
 * 2. Scans the local `blog_data.json` for chunks with pre-calculated embeddings.
 * 3. Calculates the cosine similarity between the query embedding and each chunk's embedding.
 * 4. Filters out chunks with low similarity (below 0.5) to reduce noise.
 * 5. Sorts the remaining chunks by similarity score in descending order.
 * 6. Returns the top 5 most relevant chunks.
 *
 * @param query - The user's search query or question.
 * @param apiKey - The Google Gemini API key.
 * @param customEmbedder - Optional custom function to generate embeddings (for testing).
 * @returns A promise resolving to an array of the top 5 relevant text chunks.
 */
export async function getRelevantContext(
  query: string,
  apiKey: string,
  customEmbedder?: (text: string) => Promise<number[]>,
  customData?: BlogChunk[]
): Promise<RelevantChunk[]> {
  try {
    let queryEmbedding: number[];

    if (customEmbedder) {
      queryEmbedding = await customEmbedder(query);
    } else {
      const ai = new GoogleGenAI({ apiKey });
      // Generate embedding for the query
      const response = await ai.models.embedContent({
        model: "text-embedding-004",
        contents: [{ parts: [{ text: query }] }]
      });

      if (!response.embeddings || response.embeddings.length === 0 || !response.embeddings[0].values) {
          throw new Error("No embedding returned");
      }
      queryEmbedding = response.embeddings[0].values;
    }
    const queryMagnitude = magnitude(queryEmbedding);

    // Determine data source: use injected customData (for testing) or the singleton blog index
    let data: BlogChunk[];
    if (customData) {
      // If custom data is provided, ensure we preprocess it (calculate magnitudes) just like the production path
      data = customData.reduce<BlogChunk[]>((acc, chunk) => {
        if (chunk.embedding && chunk.embedding.length > 0) {
          acc.push({
            ...chunk,
            _magnitude: magnitude(chunk.embedding)
          });
        }
        return acc;
      }, []);
    } else {
      data = getBlogData();
    }

    // Optimization: Use a single loop to calculate score and filter,
    // avoiding intermediate array allocations (map + filter).
    const scoredChunks: RelevantChunk[] = [];

    for (const chunk of data) {
      // data only contains chunks with embeddings and magnitudes, so ! assertion is safe
      const score = cosineSimilarity(queryEmbedding, chunk.embedding!, queryMagnitude, chunk._magnitude);

      // Filter by threshold (0.5) directly to avoid allocating objects for irrelevant chunks
      if (score > 0.5) {
        scoredChunks.push({
          text: chunk.text,
          title: chunk.title,
          url: chunk.url,
          score
        });
      }
    }

    // Sort by score descending (highest similarity first)
    scoredChunks.sort((a, b) => b.score - a.score);

    // Return top 5 chunks
    return scoredChunks.slice(0, 5);

  } catch (error) {
    console.error("Error retrieving relevant context:", error);
    return [];
  }
}
