
import { GoogleGenAI } from "@google/genai";
import { magnitude, cosineSimilarity } from "./vector";
import { Language } from "../types";

/**
 * @fileoverview RAG (Retrieval-Augmented Generation) Logic
 *
 * This module handles the retrieval part of the RAG pipeline. It:
 * 1. Takes a user query.
 * 2. Generates an embedding for that query using Google's Gemini Text Embedding model.
 * 3. Compares the query embedding against a database of pre-calculated embeddings (from blog posts).
 * 4. Returns the most semantically similar text chunks to be used as context for the LLM.
 *
 * Dependencies:
 * - `blog_data.json`: A JSON file generated by `scripts/ingest_blog.ts` containing text chunks and their embeddings.
 */

export interface BlogChunk {
  id: string;
  text: string;
  url: string;
  title: string;
  publishedDate: string;
  embedding?: number[] | Float32Array;
  // Optimization: Pre-calculated magnitude for the embedding
  _magnitude?: number;
  language?: string;
}

export interface RelevantChunk {
  text: string;
  title: string;
  url: string;
  score: number;
}

// Lazy initialization of blog data with magnitudes
let cachedBlogData: BlogChunk[] | null = null;

const getBlogData = async (): Promise<BlogChunk[]> => {
  if (cachedBlogData) return cachedBlogData;

  const { default: blogData } = await import("./blog_data.json");

  // Optimization: Filter out chunks without embeddings during initialization
  // and pre-calculate magnitude for valid chunks.
  // This avoids checking `chunk.embedding` exists in the hot loop.
  cachedBlogData = (blogData as BlogChunk[]).reduce<BlogChunk[]>((acc, chunk) => {
    if (chunk.embedding && chunk.embedding.length > 0) {
      // Optimization: Convert to Float32Array for memory efficiency
      const embedding = new Float32Array(chunk.embedding);
      acc.push({
        ...chunk,
        embedding,
        _magnitude: magnitude(embedding)
      });
    }
    return acc;
  }, []);

  return cachedBlogData;
};

/**
 * Retrieves relevant context chunks for a given query.
 *
 * This function performs the following steps:
 * 1. Embeds the user's query using the `text-embedding-004` model.
 * 2. Scans the local `blog_data.json` for chunks with pre-calculated embeddings.
 * 3. Calculates the cosine similarity between the query embedding and each chunk's embedding.
 * 4. Filters out chunks with low similarity (below 0.5) to reduce noise.
 * 5. Sorts the remaining chunks by similarity score in descending order.
 * 6. Returns the top 5 most relevant chunks.
 *
 * @param query - The user's search query or question.
 * @param apiKey - The Google Gemini API key.
 * @param language - The language to filter chunks by (default EN).
 * @param customEmbedder - Optional custom function to generate embeddings (for testing).
 * @param customData - Optional array of blog chunks to use instead of the file system (for testing).
 * @returns A promise resolving to an array of the top 5 relevant text chunks.
 */
export async function getRelevantContext(
  query: string,
  apiKey: string,
  language: Language = Language.EN,
  customEmbedder?: (text: string) => Promise<number[]>,
  customData?: BlogChunk[]
): Promise<RelevantChunk[]> {
  try {
    let queryEmbedding: number[] | Float32Array;

    if (customEmbedder) {
      queryEmbedding = await customEmbedder(query);
    } else {
      const ai = new GoogleGenAI({ apiKey });
      // Generate embedding for the query
      const response = await ai.models.embedContent({
        model: "text-embedding-004",
        contents: [{ parts: [{ text: query }] }]
      });

      if (!response.embeddings || response.embeddings.length === 0 || !response.embeddings[0].values) {
          throw new Error("No embedding returned");
      }
      queryEmbedding = response.embeddings[0].values;
    }

    // Optimization: Convert query to Float32Array
    if (!(queryEmbedding instanceof Float32Array)) {
        queryEmbedding = new Float32Array(queryEmbedding);
    }

    const queryMagnitude = magnitude(queryEmbedding);
    const data = customData || await getBlogData();

    // Optimization: Use a single loop to calculate score and filter,
    // avoiding intermediate array allocations (map + filter).
    const scoredChunks: RelevantChunk[] = [];

    for (const chunk of data) {
      // Ensure embedding exists before calculation (important for customData or corrupted ingestion)
      if (!chunk.embedding) continue;

      // Filter by language
      const chunkLang = chunk.language || Language.EN;
      if (chunkLang !== language) continue;

      const score = cosineSimilarity(queryEmbedding, chunk.embedding, queryMagnitude, chunk._magnitude);

      // Filter by threshold (0.5) directly to avoid allocating objects for irrelevant chunks
      if (score > 0.5) {
        scoredChunks.push({
          text: chunk.text,
          title: chunk.title,
          url: chunk.url,
          score
        });
      }
    }

    // Sort by score descending (highest similarity first)
    scoredChunks.sort((a, b) => b.score - a.score);

    // Return top 5 chunks
    return scoredChunks.slice(0, 5);

  } catch (error) {
    console.error("Error retrieving relevant context:", error);
    return [];
  }
}
